services:
  db:
    image: postgres:latest
    container_name: db_postgres
    environment:
      POSTGRES_DB: ecoenergydb
      POSTGRES_USER: ecoenergy
      POSTGRES_PASSWORD: ecoenergy123
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql
    restart: always
    networks:
      - ecoenergy-net
  
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-broker
    restart: unless-stopped
    ports:
      - "1883:1883"    
      - "9001:9001"   
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - ecoenergy-net

  backend:
    container_name: backend_app
    depends_on:
      - db
      - mosquitto
    build: ./backend
    ports:
      - "5000:5000"
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://ecoenergy:ecoenergy123@db:5432/ecoenergydb
      MQTT_BROKER_URL: tcp://mosquitto:1883
      DOCKER: "1"
    networks:
      - ecoenergy-net

  frontend:
    container_name: frontend_app
    build: ./frontend
    ports:
      - "3001:3000"   
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000 
    networks:
      - ecoenergy-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - ecoenergy-net
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3002:3000"   
    networks:
      - ecoenergy-net
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana


volumes:
  postgres_data:
  mosquitto_data:
  mosquitto_log:
  grafana-storage:

networks:
  ecoenergy-net:
    driver: bridge
