apiVersion: v1
kind: ConfigMap
metadata:
  name: ecoenergy-config
data:
  DATABASE_URL: postgresql://ecoenergy:ecoenergy123@db-service:5432/ecoenergydb
  MQTT_BROKER_URL: tcp://mosquitto-service:1883
  NEXT_PUBLIC_API_URL: http://backend-service:5000
  POSTGRES_DB: ecoenergydb
